[ADD] openacademy: Unitest about course and session constrains were a…
CDanielSanSeg/OpenAcademyCourse pull request #4
Opened 2022-10-14 23:59 UTC by CDanielSanSeg

…dded. Files for unitest are:

    - open_academy/tests/__init__.py
    - open_academy/tests/test_global_openacademy_course.py
    - open_academy/tests/test_global_openacademy_session.py
    - open_academy/views/open_academy_session_views.xml

2022-10-15 00:00 UTC, CDanielSanSeg commented
Hi @edy1192, can you check this PR?

[ADD] openacademy: Unitest about course and session constrains were added. Files for unitest are:

    - open_academy/tests/__init__.py
    - open_academy/tests/test_global_openacademy_course.py
    - open_academy/tests/test_global_openacademy_session.py
    - open_academy/views/open_academy_session_views.xml

2022-10-17 14:43 UTC, edy1192 requested changes

2022-10-17 14:43 UTC, edy1192 commented on open_academy/models/open_academy_course.py
> +        pass
Why this?

2022-10-17 14:43 UTC, edy1192 commented on open_academy/tests/test_global_openacademy_session.py
> +class GlobalTestOpenAcademyCourse(TransactionCase):
```suggestion
class GlobalTestOpenAcademySession(TransactionCase):
```

2022-10-17 16:04 UTC, CDanielSanSeg commented
@edy1192 can you check the changes in this PR?

2022-10-17 16:47 UTC, edy1192 approved these changes

2022-10-17 16:48 UTC, merged